import { describe, it, expect, vi } from 'vitest';

vi.mock('../server/db.ts', () => {
  throw new Error('db.ts must not be imported by import-history parser tests');
});

import {
  parseSession,
  realPrompt,
  titleFromPrompt,
  truncateTitle,
  capInput,
  matchChannel,
  encodeProjectDir,
  RESULT_MAX,
} from '../scripts/lib/claude-session.ts';

const SID = '8971a660-ea2e-483e-853f-12de037d1136';
let n = 0;
const base = (over: Record<string, unknown>) => ({
  sessionId: SID,
  cwd: '/Users/ben/phillbert',
  entrypoint: 'claude-desktop',
  uuid: `u-${++n}`,
  isSidechain: false,
  ...over,
});
const user = (content: unknown, ts: string, over: Record<string, unknown> = {}) =>
  base({ type: 'user', timestamp: ts, message: { role: 'user', content }, ...over });
const assistant = (content: unknown[], ts: string, over: Record<string, unknown> = {}) =>
  base({ type: 'assistant', timestamp: ts, message: { role: 'assistant', content }, ...over });
const jsonl = (...lines: unknown[]) => lines.map((l) => JSON.stringify(l)).join('\n') + '\n';

describe('realPrompt', () => {
  it('keeps plain prompts', () => {
    expect(realPrompt('  fix the header  ')).toEqual({ text: 'fix the header', command: false });
  });

  it.each([
    '<local-command-stdout>Set model to opus</local-command-stdout>',
    '<bash-input>ls</bash-input><bash-stdout>a</bash-stdout><bash-stderr></bash-stderr>',
    '<task-notification>\n<task-id>x</task-id></task-notification>',
    '[Request interrupted by user]',
    '[Request interrupted by user for tool use]',
    'Caveat: The messages below were generated by the user while running local commands. DO NOT respond.',
    '<system-reminder>\nscratch workspace\n</system-reminder>',
    '   ',
  ])('drops harness plumbing: %s', (text) => {
    expect(realPrompt(text)).toBeNull();
  });

  it('drops built-in slash commands', () => {
    expect(realPrompt('<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args>opus</command-args>')).toBeNull();
    expect(realPrompt('<command-name>/compact</command-name><command-message>compact</command-message><command-args></command-args>')).toBeNull();
  });

  it('turns skill slash commands into /name args', () => {
    const p = realPrompt(
      '<command-message>volero-master-import</command-message>\n<command-name>/volero-master-import</command-name>\n<command-args>catch up on new products</command-args>',
    );
    expect(p).toEqual({ text: '/volero-master-import catch up on new products', command: true });
    expect(realPrompt('<command-message>x</command-message>\n<command-name>/commit-commands:commit-push-pr</command-name>')).toEqual({
      text: '/commit-commands:commit-push-pr',
      command: true,
    });
  });

  it('strips system reminders but keeps the typed prompt after them', () => {
    expect(realPrompt('<system-reminder>\nnote\n</system-reminder>\n\nship it')).toEqual({ text: 'ship it', command: false });
  });
});

describe('titleFromPrompt', () => {
  it('uses the first line and truncates to 80 chars', () => {
    expect(titleFromPrompt('Fix the cart drawer\nmore detail')).toBe('Fix the cart drawer');
    const long = titleFromPrompt('word '.repeat(40));
    expect(long.length).toBeLessThanOrEqual(80);
    expect(long.endsWith('...')).toBe(true);
  });

  it('skips selected-element and annotation context blocks', () => {
    expect(
      titleFromPrompt('<launch-selected-element>\n<element tag="ul">x</element>\n</launch-selected-element>\n\nallow these elements to be full width'),
    ).toBe('allow these elements to be full width');
    expect(
      titleFromPrompt('<preview-annotation-context>The attached image is a screenshot.</preview-annotation-context>\n\nweird spacing when elements wrap?'),
    ).toBe('weird spacing when elements wrap?');
  });

  it('names desktop command wrappers and strips remaining tags', () => {
    expect(titleFromPrompt('<create-pr-command>\n## Overview\nCreate a PR</create-pr-command>')).toBe('Create pr');
    expect(titleFromPrompt('<pasted_content id="ea6c">\nI want one place for agents</pasted_content>')).toBe('I want one place for agents');
    expect(titleFromPrompt('<a onclick="x()" href="#">Privacy settings</a>\n\nI need a button')).toBe('Privacy settings');
  });

  it('truncateTitle collapses whitespace', () => {
    expect(truncateTitle('  a \n\t b  ')).toBe('a b');
    expect(truncateTitle('x'.repeat(81))).toBe('x'.repeat(77) + '...');
    expect(truncateTitle('x'.repeat(80))).toBe('x'.repeat(80));
  });
});

describe('parseSession', () => {
  it('builds user, assistant, tool_use and tool_result events with timestamps', () => {
    const src = jsonl(
      { type: 'file-history-snapshot', messageId: 'm', snapshot: {} },
      user('caffeinate may still be on, turn it off', '2026-08-29T13:35:44.126Z'),
      assistant([{ type: 'thinking', thinking: '...' }], '2026-08-29T13:35:46.000Z'),
      assistant([{ type: 'tool_use', id: 'toolu_1', name: 'Bash', input: { command: 'pgrep -fl caffeinate' } }], '2026-08-29T13:35:47.847Z'),
      user([{ type: 'tool_result', tool_use_id: 'toolu_1', content: '7168 caffeinate -dimsu', is_error: false }], '2026-08-29T13:35:48.359Z', {
        toolUseResult: { stdout: '7168' },
      }),
      assistant([{ type: 'text', text: 'Killed it.' }], '2026-08-29T13:35:55.302Z'),
      { type: 'ai-title', sessionId: SID, aiTitle: 'Caffeinate process cleanup' },
    );
    const s = parseSession(src, '-Users-ben-phillbert');
    expect(s.sessionId).toBe(SID);
    expect(s.cwd).toBe('/Users/ben/phillbert');
    expect(s.title).toBe('Caffeinate process cleanup');
    expect(s.prompts).toBe(1);
    expect(s.createdAt).toBe('2026-08-29T13:35:44.126Z');
    expect(s.updatedAt).toBe('2026-08-29T13:35:55.302Z');
    expect(s.entrypoint).toBe('claude-desktop');
    expect(s.events).toEqual([
      { kind: 'user', payload: { text: 'caffeinate may still be on, turn it off', source: 'import' }, createdAt: '2026-08-29T13:35:44.126Z' },
      {
        kind: 'tool_use',
        payload: { id: 'toolu_1', name: 'Bash', input: { command: 'pgrep -fl caffeinate' }, parent: null },
        createdAt: '2026-08-29T13:35:47.847Z',
      },
      {
        kind: 'tool_result',
        payload: { tool_use_id: 'toolu_1', text: '7168 caffeinate -dimsu', is_error: false, truncated: false },
        createdAt: '2026-08-29T13:35:48.359Z',
      },
      { kind: 'assistant_text', payload: { text: 'Killed it.' }, createdAt: '2026-08-29T13:35:55.302Z' },
    ]);
    expect(s.lastText).toBe('Killed it.');
  });

  it('prefers custom title over summary over ai title over the first prompt', () => {
    const prompt = user('first real prompt', '2026-09-01T00:00:00.000Z');
    expect(parseSession(jsonl(prompt)).title).toBe('first real prompt');
    expect(parseSession(jsonl(prompt, { type: 'ai-title', aiTitle: 'AI' })).title).toBe('AI');
    expect(parseSession(jsonl({ type: 'summary', summary: 'Sum', leafUuid: 'x' }, prompt, { type: 'ai-title', aiTitle: 'AI' })).title).toBe('Sum');
    expect(
      parseSession(jsonl({ type: 'summary', summary: 'Sum' }, prompt, { type: 'custom-title', customTitle: 'Old' }, { type: 'custom-title', customTitle: 'Mine' }))
        .title,
    ).toBe('Mine');
  });

  it('skips plumbing: meta, compact summaries, task notifications, builtin commands, sidechains', () => {
    const src = jsonl(
      user('Caveat: The messages below were generated by the user while running local commands.', '2026-09-01T00:00:00.000Z', { isMeta: true }),
      user('<command-name>/model</command-name><command-message>model</command-message><command-args>opus</command-args>', '2026-09-01T00:00:01.000Z'),
      user('<local-command-stdout>Set model to opus</local-command-stdout>', '2026-09-01T00:00:02.000Z'),
      user('This session is being continued from a previous conversation...', '2026-09-01T00:00:03.000Z', { isCompactSummary: true }),
      user('<task-notification><task-id>b1</task-id></task-notification>', '2026-09-01T00:00:04.000Z', { origin: { kind: 'task-notification' } }),
      user('sub-agent brief', '2026-09-01T00:00:05.000Z', { isSidechain: true }),
      assistant([{ type: 'text', text: 'sub-agent reply' }], '2026-09-01T00:00:06.000Z', { isSidechain: true }),
      user([{ type: 'text', text: '[Request interrupted by user]' }], '2026-09-01T00:00:07.000Z'),
    );
    const s = parseSession(src);
    expect(s.prompts).toBe(0);
    expect(s.events).toEqual([]);
    expect(s.title).toBe('Imported session');
  });

  it('keeps tool results from injected turns but not their prompt text', () => {
    const s = parseSession(
      jsonl(
        user(
          [
            { type: 'tool_result', tool_use_id: 't', content: 'ok' },
            { type: 'text', text: '<task-notification>done</task-notification>' },
          ],
          '2026-09-01T00:00:00.000Z',
          { origin: { kind: 'task-notification' } },
        ),
      ),
    );
    expect(s.events.map((e) => e.kind)).toEqual(['tool_result']);
    expect(s.prompts).toBe(0);
  });

  it('uses a skill command as the title only when there is no plain prompt', () => {
    const cmd = user(
      '<command-message>ecomm-cro-expert</command-message>\n<command-name>/ecomm-cro-expert</command-name>\n<command-args>https://example.com/</command-args>',
      '2026-09-01T00:00:00.000Z',
    );
    expect(parseSession(jsonl(cmd)).title).toBe('/ecomm-cro-expert https://example.com/');
    expect(parseSession(jsonl(cmd)).prompts).toBe(1);
    expect(parseSession(jsonl(cmd, user('now do the checkout page', '2026-09-01T00:01:00.000Z'))).title).toBe('now do the checkout page');
  });

  it('does not title a session with the auto-resume nudge when a real prompt exists', () => {
    const s = parseSession(
      jsonl(
        user('The app was quit while you were working. Please continue from where you left off.', '2026-09-01T00:00:00.000Z'),
        user('check the order import', '2026-09-01T00:01:00.000Z'),
      ),
    );
    expect(s.title).toBe('check the order import');
    expect(s.prompts).toBe(2);
  });

  it('truncates tool results over 4000 chars and joins array content', () => {
    const s = parseSession(
      jsonl(
        user('go', '2026-09-01T00:00:00.000Z'),
        user(
          [
            { type: 'tool_result', tool_use_id: 'a', content: 'z'.repeat(RESULT_MAX + 1), is_error: true },
            { type: 'tool_result', tool_use_id: 'b', content: [{ type: 'text', text: 'one' }, { type: 'image' }, { type: 'text', text: 'two' }] },
          ],
          '2026-09-01T00:00:01.000Z',
        ),
      ),
    );
    const [a, b] = s.events.filter((e) => e.kind === 'tool_result');
    expect(a.payload).toMatchObject({ tool_use_id: 'a', is_error: true, truncated: true });
    expect((a.payload.text as string).length).toBe(RESULT_MAX);
    expect(b.payload).toEqual({ tool_use_id: 'b', text: 'one\n[image]\ntwo', is_error: false, truncated: false });
  });

  it('caps huge strings inside tool inputs', () => {
    const s = parseSession(
      jsonl(
        user('write it', '2026-09-01T00:00:00.000Z'),
        assistant([{ type: 'tool_use', id: 'w', name: 'Write', input: { file_path: '/x', content: 'a'.repeat(10_000) } }], '2026-09-01T00:00:01.000Z'),
      ),
    );
    const input = s.events[1].payload.input as { file_path: string; content: string };
    expect(input.file_path).toBe('/x');
    expect(input.content.length).toBeLessThan(4100);
    expect(input.content).toContain('[truncated 6000 chars]');
  });

  it('maps API error messages to error events', () => {
    const s = parseSession(
      jsonl(
        user('hi', '2026-09-01T00:00:00.000Z'),
        assistant([{ type: 'text', text: 'API Error: 529 overloaded' }], '2026-09-01T00:00:01.000Z', { isApiErrorMessage: true }),
      ),
    );
    expect(s.events[1]).toMatchObject({ kind: 'error', payload: { text: 'API Error: 529 overloaded' } });
    expect(s.lastText).toBeNull();
  });

  it('counts image-only prompts and notes images next to text', () => {
    const s = parseSession(
      jsonl(
        user([{ type: 'image', source: {} }], '2026-09-01T00:00:00.000Z'),
        user([{ type: 'text', text: 'what is wrong here' }, { type: 'image', source: {} }], '2026-09-01T00:00:01.000Z'),
      ),
    );
    expect(s.prompts).toBe(2);
    expect(s.events.map((e) => e.payload.text)).toEqual(['[image]', 'what is wrong here\n\n[image]']);
    expect(s.title).toBe('what is wrong here');
  });

  it('dedupes repeated uuids and tolerates torn lines', () => {
    const line = user('once', '2026-09-01T00:00:00.000Z');
    const s = parseSession(JSON.stringify(line) + '\n' + JSON.stringify(line) + '\n{"type":"assistant","mess');
    expect(s.events.length).toBe(1);
  });

  it('picks the cwd that matches the project dir (case-insensitively), else relocated, else the first', () => {
    const lines = jsonl(
      user('a', '2026-09-01T00:00:00.000Z', { cwd: '/Users/ben/phillbert' }),
      user('b', '2026-09-01T00:00:01.000Z', { cwd: '/Users/ben/phillbert/projects/volero' }),
    );
    expect(parseSession(lines, '-Users-ben-PHILLBERT').cwd).toBe('/Users/ben/phillbert');
    expect(parseSession(lines, '-Users-ben-phillbert-projects-volero').cwd).toBe('/Users/ben/phillbert/projects/volero');
    expect(parseSession(lines, '-somewhere-else').cwd).toBe('/Users/ben/phillbert');
    expect(parseSession(lines + JSON.stringify({ type: 'relocated', relocatedCwd: '/Users/ben/moved' }), '-nope').cwd).toBe('/Users/ben/moved');
    expect(parseSession(jsonl({ type: 'summary', summary: 's' })).cwd).toBeNull();
  });

  it('lastText is the assistant text after the final prompt', () => {
    const s = parseSession(
      jsonl(
        user('one', '2026-09-01T00:00:00.000Z'),
        assistant([{ type: 'text', text: 'first answer' }], '2026-09-01T00:00:01.000Z'),
        user('two', '2026-09-01T00:00:02.000Z'),
        assistant([{ type: 'text', text: 'part A' }], '2026-09-01T00:00:03.000Z'),
        assistant([{ type: 'text', text: 'part B' }], '2026-09-01T00:00:04.000Z'),
      ),
    );
    expect(s.lastText).toBe('part A\n\npart B');
  });
});

describe('capInput', () => {
  it('leaves small values alone and recurses into arrays and objects', () => {
    expect(capInput({ a: 1, b: 'x', c: [true, null, 'y'] })).toEqual({ a: 1, b: 'x', c: [true, null, 'y'] });
    expect((capInput({ edits: [{ old: 'q'.repeat(20) }] }, 5) as any).edits[0].old).toMatch(/^q{5}\n\.\.\. \[truncated 15 chars\]$/);
  });
});

describe('encodeProjectDir', () => {
  it('matches Claude Code project dir naming', () => {
    expect(encodeProjectDir('/Users/benrosenberg/omni-os/data/worktrees/5a60')).toBe('-Users-benrosenberg-omni-os-data-worktrees-5a60');
    expect(encodeProjectDir('/Users/b/apa-volero/.claude/worktrees/x')).toBe('-Users-b-apa-volero--claude-worktrees-x');
  });
});

describe('matchChannel', () => {
  const chans = [
    { id: 'volero', repo_path: '/Users/ben/apa-volero', base_dir: null },
    { id: 'volero-ops', repo_path: null, base_dir: '/Users/ben/phillbert/projects/volero' },
    { id: 'brain', repo_path: null, base_dir: '/Users/ben/phillbert/' },
  ];

  it('matches equal paths and subdirectories', () => {
    expect(matchChannel('/Users/ben/apa-volero', chans)?.id).toBe('volero');
    expect(matchChannel('/Users/ben/apa-volero/.claude/worktrees/pr263', chans)?.id).toBe('volero');
  });

  it('prefers the longest prefix', () => {
    expect(matchChannel('/Users/ben/phillbert/projects/volero/feed-import', chans)?.id).toBe('volero-ops');
    expect(matchChannel('/Users/ben/phillbert/projects/acne', chans)?.id).toBe('brain');
  });

  it('does not match sibling dirs that share a prefix string', () => {
    expect(matchChannel('/Users/ben/apa-volero-2', chans)).toBeUndefined();
  });

  it('is case-insensitive like APFS', () => {
    expect(matchChannel('/Users/ben/PHILLBERT', chans)?.id).toBe('brain');
  });
});
