// Pure parser for Claude Code session transcripts (~/.claude/projects/<dir>/<session>.jsonl).
// No I/O and no db.ts import, so tests can exercise it directly.

export interface ImportEvent {
  kind: 'user' | 'assistant_text' | 'tool_use' | 'tool_result' | 'error';
  payload: Record<string, unknown>;
  createdAt: string;
}

export interface ParsedSession {
  sessionId: string | null;
  cwd: string | null;
  title: string;
  entrypoint: string | null;
  createdAt: string | null;
  updatedAt: string | null;
  prompts: number;
  events: ImportEvent[];
  lastText: string | null;
}

export const TITLE_MAX = 80;
export const RESULT_MAX = 4000;
/** Per-string cap inside tool_use inputs. Write/Edit calls can carry whole files. */
export const INPUT_STRING_MAX = 4000;

/** Claude Code's project dir name for a cwd. */
export const encodeProjectDir = (cwd: string) => cwd.replace(/[^a-zA-Z0-9]/g, '-');

// Built-in slash commands are session plumbing, not prompts.
const BUILTIN_COMMANDS = new Set([
  'add-dir', 'agents', 'bashes', 'clear', 'color', 'compact', 'config', 'context', 'cost', 'doctor', 'effort',
  'exit', 'export', 'fast', 'help', 'hooks', 'ide', 'login', 'logout', 'mcp', 'memory', 'model', 'output-style',
  'permissions', 'plugin', 'plugins', 'privacy-settings', 'quit', 'release-notes', 'reload-plugins', 'rename',
  'resume', 'rewind', 'sandbox', 'skills', 'status', 'statusline', 'tasks', 'terminal-setup', 'theme', 'todos',
  'upgrade', 'usage', 'vim',
]);

// Lines that start with these are harness output, not something Ben typed.
const NON_PROMPT_PREFIXES = [
  '<local-command-stdout>', '<local-command-stderr>', '<local-command-caveat>', '<bash-input>', '<bash-stdout>',
  '<bash-stderr>', '<task-notification>', '<user-memory-input>', '[Request interrupted by user',
  'Caveat: The messages below were generated by the user while running local commands',
];

const SYSTEM_REMINDER = /<system-reminder>[\s\S]*?<\/system-reminder>/g;

// Context blocks the harness prepends to a real prompt.
const CONTEXT_BLOCK = /<(system-reminder|preview-annotation-context|launch-selected-element|ide_opened_file|ide_selection|ide_diagnostics)\b[^>]*>[\s\S]*?<\/\1>/g;

// Real prompts that make bad titles.
const WEAK_TITLE = [/^The app was quit while you were working/i, /^\[image\]$/];

type Block = { type?: string; text?: string; id?: string; name?: string; input?: unknown; tool_use_id?: string; content?: unknown; is_error?: boolean };

export function truncateTitle(s: string, max = TITLE_MAX) {
  const flat = s.replace(/\s+/g, ' ').trim();
  return flat.length > max ? flat.slice(0, max - 3).trimEnd() + '...' : flat;
}

/** Turns a slash-command wrapper into "/name args", or null for built-ins / non-commands. */
export function parseCommand(text: string): { command: string; text: string } | null {
  const name = text.match(/<command-name>\s*\/?([^<\s]+)\s*<\/command-name>/)?.[1];
  if (!name) return null;
  const args = text.match(/<command-args>([\s\S]*?)<\/command-args>/)?.[1]?.trim() ?? '';
  return { command: name, text: `/${name}${args ? ' ' + args : ''}` };
}

export interface PromptInfo {
  text: string;
  /** Came from a slash-command wrapper; only used as a title when nothing better exists. */
  command: boolean;
}

/** Returns the prompt Ben typed, or null if this user text is harness plumbing. */
export function realPrompt(raw: string): PromptInfo | null {
  // Reminders are injected by the harness; drop them and see if Ben typed anything.
  const s = raw.replace(SYSTEM_REMINDER, '').trim();
  if (!s) return null;
  if (s.startsWith('<command-name>') || s.startsWith('<command-message>')) {
    const cmd = parseCommand(s);
    if (!cmd || BUILTIN_COMMANDS.has(cmd.command)) return null;
    return { text: cmd.text, command: true };
  }
  if (NON_PROMPT_PREFIXES.some((p) => s.startsWith(p))) return null;
  return { text: s, command: false };
}

/** A readable one-line title from a prompt that may carry XML-ish wrappers. */
export function titleFromPrompt(prompt: string): string {
  let s = prompt.replace(CONTEXT_BLOCK, ' ').trim();
  const cmdTag = s.match(/^<([a-z][a-z0-9-]*)-command>/i);
  if (cmdTag) {
    const words = cmdTag[1].replace(/-/g, ' ');
    return truncateTitle(words.charAt(0).toUpperCase() + words.slice(1));
  }
  s = s.replace(/<\/?[a-zA-Z][\w-]*(\s[^>]*)?>/g, ' ');
  const line = s.split('\n').map((l) => l.trim()).find(Boolean) ?? '';
  return truncateTitle(line);
}

function blockText(content: unknown): string {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) {
    return content
      .map((c: Block) => (c?.type === 'text' ? c.text ?? '' : c?.type === 'image' ? '[image]' : ''))
      .filter(Boolean)
      .join('\n');
  }
  return content == null ? '' : JSON.stringify(content);
}

/** Caps every string inside a tool input so a Write of a 2 MB file does not land in the DB. */
export function capInput(value: unknown, max = INPUT_STRING_MAX): unknown {
  if (typeof value === 'string') return value.length > max ? value.slice(0, max) + `\n... [truncated ${value.length - max} chars]` : value;
  if (Array.isArray(value)) return value.map((v) => capInput(v, max));
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, capInput(v, max)]));
  }
  return value;
}

function pickCwd(cwds: string[], relocated: string[], dirName?: string): string | null {
  const matches = (c: string) => !!dirName && encodeProjectDir(c).toLowerCase() === dirName.toLowerCase();
  // The session file lives in the dir for the cwd Claude Code will --resume from.
  return (
    [...relocated].reverse().find(matches) ??
    cwds.find(matches) ??
    relocated[relocated.length - 1] ??
    cwds[0] ??
    null
  );
}

/**
 * Parses one transcript. `dirName` is the ~/.claude/projects/<dirName> folder, used to pick the cwd
 * that matches where the session file lives (the cwd can change mid-session).
 */
export function parseSession(src: string, dirName?: string): ParsedSession {
  const cwds: string[] = [];
  const relocated: string[] = [];
  const events: ImportEvent[] = [];
  const seen = new Set<string>();
  let sessionId: string | null = null;
  let entrypoint: string | null = null;
  let firstTs: string | null = null;
  let lastTs: string | null = null;
  let customTitle: string | null = null;
  let summary: string | null = null;
  let aiTitle: string | null = null;
  let promptTitle: string | null = null;
  let commandTitle: string | null = null;
  let weakTitle: string | null = null;
  let prompts = 0;

  for (const line of src.split('\n')) {
    if (!line.trim()) continue;
    let e: any;
    try {
      e = JSON.parse(line);
    } catch {
      continue; // a torn last line while the session is still being written
    }
    if (!e || typeof e !== 'object') continue;

    if (typeof e.timestamp === 'string' && !Number.isNaN(Date.parse(e.timestamp))) {
      const ts = new Date(e.timestamp).toISOString();
      if (!firstTs || ts < firstTs) firstTs = ts;
      if (!lastTs || ts > lastTs) lastTs = ts;
    }
    const ts = typeof e.timestamp === 'string' ? e.timestamp : lastTs ?? '';

    if (e.sessionId && !sessionId) sessionId = e.sessionId;
    if (typeof e.cwd === 'string' && e.cwd && !cwds.includes(e.cwd)) cwds.push(e.cwd);
    if (e.entrypoint && !entrypoint) entrypoint = e.entrypoint;

    switch (e.type) {
      case 'custom-title':
        if (e.customTitle) customTitle = String(e.customTitle);
        continue;
      case 'summary':
        if (e.summary) summary = String(e.summary);
        continue;
      case 'ai-title':
        if (e.aiTitle) aiTitle = String(e.aiTitle);
        continue;
      case 'relocated':
        if (e.relocatedCwd) relocated.push(String(e.relocatedCwd));
        continue;
    }

    if (e.type !== 'user' && e.type !== 'assistant') continue;
    if (e.isSidechain) continue;
    if (e.uuid) {
      if (seen.has(e.uuid)) continue;
      seen.add(e.uuid);
    }
    const content = e.message?.content;

    if (e.type === 'assistant') {
      if (!Array.isArray(content)) continue;
      for (const b of content as Block[]) {
        if (b?.type === 'text' && b.text?.trim()) {
          events.push({ kind: e.isApiErrorMessage ? 'error' : 'assistant_text', payload: { text: b.text }, createdAt: ts });
        } else if (b?.type === 'tool_use' && b.id) {
          events.push({
            kind: 'tool_use',
            payload: { id: b.id, name: b.name ?? 'tool', input: capInput(b.input), parent: null },
            createdAt: ts,
          });
        }
      }
      continue;
    }

    // user
    if (e.isMeta || e.isCompactSummary || e.isVisibleInTranscriptOnly) continue;
    // Task notifications and other injected turns are not prompts (tool results still count).
    const injected = !!e.origin?.kind && e.origin.kind !== 'human';
    const texts: string[] = [];
    let images = 0;
    if (typeof content === 'string') texts.push(content);
    else if (Array.isArray(content)) {
      for (const b of content as Block[]) {
        if (b?.type === 'tool_result') {
          const text = blockText(b.content);
          events.push({
            kind: 'tool_result',
            payload: {
              tool_use_id: b.tool_use_id,
              text: text.length > RESULT_MAX ? text.slice(0, RESULT_MAX) : text,
              is_error: !!b.is_error,
              truncated: text.length > RESULT_MAX,
            },
            createdAt: ts,
          });
        } else if (b?.type === 'text' && b.text) texts.push(b.text);
        else if (b?.type === 'image') images++;
      }
    }
    if (injected || (!texts.length && !images)) continue;
    const joined = texts.join('\n\n');
    const p = texts.length ? realPrompt(joined) : { text: '[image]', command: false };
    if (!p) continue;
    const text = images && texts.length ? `${p.text}\n\n${'[image] '.repeat(images).trim()}` : p.text;
    prompts++;
    events.push({ kind: 'user', payload: { text, source: 'import' }, createdAt: ts });
    const t = titleFromPrompt(p.text);
    if (!t) continue;
    if (p.command) commandTitle ??= t;
    else if (WEAK_TITLE.some((re) => re.test(t))) weakTitle ??= t;
    else promptTitle ??= t;
  }

  // Backfill events that came before the first timestamped line.
  for (const ev of events) if (!ev.createdAt) ev.createdAt = firstTs ?? '';

  const title = truncateTitle(customTitle ?? summary ?? aiTitle ?? promptTitle ?? commandTitle ?? weakTitle ?? 'Imported session');

  // Same rule as the runner: last_text is the assistant text after the final user prompt.
  const lastUser = events.map((ev) => ev.kind).lastIndexOf('user');
  const tail = events
    .slice(lastUser + 1)
    .filter((ev) => ev.kind === 'assistant_text')
    .map((ev) => ev.payload.text as string)
    .join('\n\n');

  return {
    sessionId,
    cwd: pickCwd(cwds, relocated, dirName),
    title,
    entrypoint,
    createdAt: firstTs,
    updatedAt: lastTs,
    prompts,
    events,
    lastText: tail ? tail.slice(0, 600) : null,
  };
}

/** Longest repo_path/base_dir that equals the cwd or contains it. */
export function matchChannel<C extends { id: string; repo_path: string | null; base_dir: string | null }>(
  cwd: string,
  channels: C[],
): C | undefined {
  const norm = (p: string) => p.replace(/\/+$/, '').toLowerCase();
  const target = norm(cwd);
  let best: { ch: C; len: number } | undefined;
  for (const ch of channels) {
    for (const p of [ch.repo_path, ch.base_dir]) {
      if (!p) continue;
      const base = norm(p);
      if (!base) continue;
      if (target === base || target.startsWith(base + '/')) {
        if (!best || base.length > best.len) best = { ch, len: base.length };
      }
    }
  }
  return best?.ch;
}
